<?php

namespace IGBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupIGRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupIGRepository extends EntityRepository
{
}
