<?php

namespace IGBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InstantWinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstantWinRepository extends EntityRepository
{
}
